type == disk

diff --git a/scripts/SRCD/wipe_all_drives b/scripts/SRCD/wipe_all_drives
--- a/scripts/SRCD/wipe_all_drives
+++ b/scripts/SRCD/wipe_all_drives
@@ -20,11 +20,22 @@ die() {
 }
 
 
+warn() {
+  logr "WARN: $*"
+}
+
+info() {
+  logr "INFO: $*"
+}
+
+
 get_valid_devs() {
   # if TRAN is null, then it's a partition or virtual device
   # if TRAN is usb, then it's a USB device (dont wipe the boot USB key)
-  lsblk -o kname,tran --paths --json \
-  | jq -r '.blockdevices[] | select(.tran != null and .tran != "usb") | .kname'
+  lsblk -o kname,tran,type --paths --json \
+  | jq -r '.blockdevices[] 
+    | select(.type == "disk" and .tran != null and .tran != "usb")
+    | .kname'
 }
 
 
@@ -33,13 +44,13 @@ wipe_device() {
   local _action=shred
   local _parms=( "--iterations=1" "--force" "--zero" )
   [[ $DEBUG -eq 1 ]] && _action='echo'
-  logr "$(date) START $_full_path_to_device"
-  logr "$_action ${_parms[@]} $_full_path_to_device"
+  info "$(date) START $_full_path_to_device"
+  info "$_action ${_parms[@]} $_full_path_to_device"
   set -x
   $_action "${_parms[@]}" "$_full_path_to_device"
   local _rc=$?
   set +x
-  logr "$(date) END $_full_path_to_device"
+  info "$(date) END $_full_path_to_device"
   return "$_rc"
 }
 
@@ -52,17 +63,19 @@ if [[ ${#devices[*]} -lt 1 ]] ; then
 fi
 
 # Show what drives were found
-logr "Found ${#devices[*]} device(s) ..."
-lsblk --paths -o kname,size "${devices[@]}" | tee -a "$LOGFILE"
+info "Found ${#devices[*]} device(s) ..."
+lsblk "${devices[@]}" \
+  | grep '^[a-zA-Z]' \
+  | tee -a "$LOGFILE"
 
 # Wipe all the drives
 for dev in "${devices[@]}"; do
-  wipe_device "${dev}" || logr "${dev} failed" &
+  wipe_device "${dev}" || warn "Wipe failed for '${dev}'" &
 done
 
 # wait for all the "shred" procs to finish
 wait
 
-logr "Done. Wiped ${#devices[*]} device(s) in ${SECONDS} seconds"
+info "Done. Wiped ${#devices[*]} device(s) in ${SECONDS} seconds"
 
 exit 0
